repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: check-json
      - id: check-yaml
        exclude: ^deployments/consumer/templates/template.yaml$
      - id: trailing-whitespace

-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.14
    hooks:
      - id: ruff
        args:
          - --fix
      - id: ruff-format
